# -*- coding: utf-8 -*-
"""TextminingKedar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10-1MnMXFbgFhzU0EbLZbmvmv24St6VRA
"""

import nltk
nltk.download('stopwords')
nltk.download('punkt')

pip install vaderSentiment

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

import statsmodels.formula.api as smf

import math 

from sklearn import metrics 
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/gdrive')

from google.colab import drive
df = pd.read_csv('/content/gdrive/My Drive/yelp.csv')
df

y = pd.get_dummies(df.stars)
print(y.head(3))

import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="ticks", color_codes=True)

sns.catplot(kind="count", palette="ch:.25", data=y);

df.groupby('1').size().plot(kind='bar')

#remove newlines in text
def preprocess(text):
    return text.replace('\n\n',' ')

#create list of all reviews with the new line symbols removed
all_reviews = []
for i in df.index:
    all_reviews.append(preprocess(df.text[i]))

#calculate tf-idf
tfidf = TfidfVectorizer()
tfidf_table = tfidf.fit_transform(all_reviews)

n_features = len(tfidf.get_feature_names())
print(n_features)

#save average tf-idf and sum of tf-idf for each review
avg_non_zero_tf_idf =[]
sum_tf_idf =[]
for i in range(len(all_reviews)):
    
    non_zero_doc_tf_idf = tfidf_table[i].tocoo().data.tolist()
    
    if len(non_zero_doc_tf_idf) ==0:
        avg_non_zero_tf_idf.append(0)
        
    else: avg_non_zero_tf_idf.append(sum(non_zero_doc_tf_idf)/len(non_zero_doc_tf_idf))
    
    sum_tf_idf.append(tfidf_table[i].tocoo().data.sum())

#calculate other features for the model

# stop_words=stopwords.words("english")

def is_not_only_punctuation(word):
    return not all([x  in string.punctuation for x in word  ]) 

n_words =[] #number of words
n_sent =[] #number of sentences
for review in all_reviews:
    word_list = nltk.word_tokenize(review)
    word_list_no_puncuation = [word for word in word_list if is_not_only_punctuation(word)]
    n_words.append(len(word_list_no_puncuation))
    n_sent.append( len(nltk.sent_tokenize(review)))
    
n_paras = []  #number of paragraphs
for i in df.index:
     n_paras.append(df.text[i].count("\n\n")+1)

#create binary variables for cool, funny, and useful - consider something cool/etc if 2+ votes
df['is_cool']= df.cool>1
df['is_funny']= df.funny>1
df['is_useful']= df.useful>1

#create binary variables for stars
df['star_1']= df.stars == 1
df['star_2']= df.stars == 2
df['star_3']= df.stars == 3
df['star_4']= df.stars == 4
df['star_5']= df.stars == 5

#save other features
df['avg_non_zero_tf_idf'] = avg_non_zero_tf_idf 
df['sum_tf_idf'] = sum_tf_idf
df['n_words']= n_words
df['n_sent']= n_sent
df['n_paras']= n_paras

df['exclaim'] = df.text.str.contains('!')

pip install cufflinks --upgrade

import cufflinks as cf
cf.go_offline()
cf.set_config_file(offline=False, world_readable=True)

lexical_diversity =[]

for review in all_reviews: 
    word_list = nltk.word_tokenize(review.lower())
    unique_word_list = set(word_list)

    lexical_diversity.append(len(unique_word_list)/len(word_list))    
df['LD']= lexical_diversity

analyzer=SentimentIntensityAnalyzer()

## to account for sentiment, we can include the results from sentinment analysis 
#into the model as features

## try both numerical (positive, negative, neutral scores) or binary
# a review can have a high amount of both positive and negative sentiment, so keep both
# positive and negtive aspects seperate instead of using compound score


neg = []
pos =[]
neu = []
for review in all_reviews:
    sent=analyzer.polarity_scores(review)

    neg.append(sent['neg'])
    pos.append(sent['pos'])
    neu.append(sent['neu'])
    
df['neg']= neg
df['pos']= pos
df['neu']= neu

df['is_neg']= df['neg']>.5
df['is_pos']= df['pos']>.5
df['is_neu']= df['neu']>.5

df['neg'].iplot(
    kind='hist',
    bins=50,
    xTitle='Neg-polarity',
    linecolor='black',
    yTitle='count',
    title='Sentiment Polarity Distribution')

df['pos'].iplot(
    kind='hist',
    bins=50,
    xTitle='Pos-polarity',
    linecolor='black',
    yTitle='count',
    title='Sentiment Polarity Distribution')

df['neu'].iplot(
    kind='hist',
    bins=50,
    xTitle='Neu-polarity',
    linecolor='black',
    yTitle='count',
    title='Sentiment Polarity Distribution')

"""### Average TF IDF over non zero values (ie only over words in the doc)

through trail and error this is the best model I found, based of R2 of test set 

coefs for cool and useful are (-) and funny is (+)
"""

#split into train and test set 

X = df[['is_pos','is_neg','is_cool','is_funny','is_useful','star_1','star_2','star_3','star_4','star_5','n_sent','n_paras','n_words']]
y = df[['avg_non_zero_tf_idf']]

# Split X and y into X_
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

#fit model
regression_model = LinearRegression(fit_intercept=True)
regression_model.fit(X_train, y_train)


for idx, col_name in enumerate(X_train.columns):
    print("The coefficient for {} is {}".format(col_name, regression_model.coef_[0][idx]))

pred=regression_model.predict(X_test) #make prediction on test set
error = math.sqrt(metrics.mean_squared_error(y_test,pred)) #calculate rmse

print('Test RMSE:: ',error)
print('Test score::',regression_model.score(X_test,y_test)) #R2 score

"""### Sum of tf-idf over all words

Cool and useful (+) and funny is (-)
"""

#split into train and test set 

X = df[['is_pos','is_neg','is_cool','is_funny','is_useful','star_1','star_2','star_3','star_4','star_5','n_sent','n_paras','n_words','exclaim']]
y = df[['sum_tf_idf']]

# Split X and y into X_
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

#fit model
regression_model = LinearRegression(fit_intercept=True)
regression_model.fit(X_train, y_train)


for idx, col_name in enumerate(X_train.columns):
    print("The coefficient for {} is {}".format(col_name, regression_model.coef_[0][idx]))

pred=regression_model.predict(X_test) #make prediction on test set
error = math.sqrt(metrics.mean_squared_error(y_test,pred)) #calculate rmse

print('Test RMSE:: ',error)
print('Test score::',regression_model.score(X_test,y_test)) #R2 score

"""### Lexical diversity

Cool and useful (-) and funny is (+)
"""

#split into train and test set 

X = df[['pos','neg','is_cool','is_funny','is_useful','star_1','star_2','star_3','star_4','star_5','n_sent','n_paras','n_words']]
y = df[['LD']]

# Split X and y into X_
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

#fit model
regression_model = LinearRegression(fit_intercept=True)
regression_model.fit(X_train, y_train)


for idx, col_name in enumerate(X_train.columns):
    print("The coefficient for {} is {}".format(col_name, regression_model.coef_[0][idx]))

pred=regression_model.predict(X_test) #make prediction on test set
error = math.sqrt(metrics.mean_squared_error(y_test,pred)) #calculate rmse

print('Test RMSE:: ',error)
print('Test score::',regression_model.score(X_test,y_test)) #R2 score

ct1 = pd.crosstab(df.is_funny,df.is_useful)
ct1.plot.bar()

ct1

ct2 = pd.crosstab(df.is_cool,df.is_useful)
ct2.plot.bar()

ct2

ct3 = pd.crosstab(df.is_funny,df.is_cool)
ct3.plot.bar()

ct3

corr = df.corr()
f, ax = plt.subplots(figsize=(11, 15)) 
heatmap = sns.heatmap(corr,
                      square = True,
                      linewidths = .5,
                      cmap = 'coolwarm',
                      cbar_kws = {'shrink': .4, 
                                'ticks' : [-1, -.5, 0, 0.5, 1]},
                      vmin = -1, 
                      vmax = 1,
                      annot = True,
                      annot_kws = {'size': 12})
#add the column names as labels
ax.set_yticklabels(corr.columns, rotation = 10)
ax.set_xticklabels(corr.columns)
sns.set_style({'xtick.bottom': True}, {'ytick.left': True})

corr = df.corr()
f, ax = plt.subplots(figsize=(11, 15)) 
heatmap = sns.heatmap(corr,
                      square = True,
                      linewidths = .5,
                      cmap = 'coolwarm',
                      cbar_kws = {'shrink': .4, 
                                'ticks' : [-1, -.5, 0, 0.5, 1]},
                      vmin = -1, 
                      vmax = 1,
                      annot = True,
                      annot_kws = {'size': 12})
#add the column names as labels
ax.set_yticklabels(corr.columns, rotation = 10)
ax.set_xticklabels(corr.columns)
sns.set_style({'xtick.bottom': True}, {'ytick.left': True})

